name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow for tags starting with 'v'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Package with CPack
      run: cpack --config build/CPackConfig.cmake -C Release

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: build/package/CubeSolver*
        overwrite: true
        file_glob: true
